LIBNAME DIR1 'C:\Study_UIC\IDS 462\DataSets' ;

**Problem 7-1;
ODS PDF FILE="C:\Users\adity\OneDrive\Documents\UIC\sas\HW4\Homework4.PDF";
DATA DIR1.BRAND;
   DO BRAND = 'BRAND A','BRAND N','BRAND T';
      DO SUBJ = 1 TO 8;
         INPUT TIME @;
         OUTPUT;
      END;
   END;
DROP SUBJ;
DATALINES;
8 10 9 11 10 10 8 12
4 7 5 5 6 7 6 4
12 8 10 10 11 9 9 12
;
PROC ANOVA DATA=DIR1.BRAND;
   TITLE "ONE WAY ANOVA OF BRAND AND WEAR OUT TIME";
   CLASS BRAND;
   MODEL TIME = BRAND;
   MEANS BRAND / SNK;
RUN;


**Problem 7-3;

DATA DIR1.BOUNCE_TEST;
   DO AGE = 'NEW', 'OLD';
      DO BRAND = 'BRAND W','BRAND P';
         DO I = 1 TO 5;
            INPUT BOUNCES @;
            OUTPUT;
         END;
      END;
   END;
   DROP I;
DATALINES;
67 72 74 82 81 75 76 80 72 73
46 44 45 51 43 63 62 66 62 60
;

PROC ANOVA DATA=DIR1.BOUNCE_TEST;
   TITLE "TWO WAY ANOVA FOR  AGE & BRAND OF TENNIS BALLS";
   CLASS AGE BRAND;
   MODEL BOUNCES = AGE | BRAND;
   MEANS AGE | BRAND;
RUN;


**Problem 7-5;
DATA DIR1.SODA;
   INPUT BRAND $ AGEGRP RATING @@;
DATALINES;
C 1 7  C 1 6  C 1 6  C 1 5  C 1 6  P 1 9  P 1 8
P 1 9  P 1 9  P 1 9  P 1 8  C 2 9  C 2 8  C 2 8
C 2 9  C 2 7  C 2 8  C 2 8  P 2 6  P 2 7  P 2 6
P 2 6  P 2 5
;
PROC GLM DATA=DIR1.SODA;
   TITLE "UNBALANCED ANOVA";
   CLASS BRAND AGEGRP;
   MODEL RATING = BRAND | AGEGRP;
   MEANS BRAND | AGEGRP;
RUN;

** Problem b;
PROC MEANS DATA=DIR1.SODA NWAY NOPRINT;
   CLASS BRAND AGEGRP;
   VAR RATING;
   OUTPUT OUT = DIR1.MEANS MEAN= ;
RUN;
SYMBOL1 VALUE=CIRCLE I=JOIN COLOR=BLACK;
SYMBOL2 VALUE=SQUARE I=JOIN COLOR=BLACK;
PROC GPLOT DATA=DIR1.MEANS;
TITLE "INTERACTION PLOT OF MEAN RATING VS AGE GROUP";
     PLOT RATING*AGEGRP = BRAND;
RUN;

***Problem c;

PROC SORT DATA=DIR1.SODA;
   BY AGEGRP;
RUN;
PROC TTEST DATA=DIR1.SODA;
TITLE "T-TEST FOR DIFFERENT AGE GROUPS";
   BY AGEGRP;
   CLASS BRAND;
   VAR RATING;
RUN;


**Problem 7-7;

PROC TTEST DATA=DIR1.BRAND;
	TITLE "ONE WAY ANOVA OF BRAND AND WEAR OUT TIME FOR BRAND A AND T";
   WHERE BRAND = 'BRAND A' OR BRAND = 'BRAND T';
   CLASS BRAND;
   VAR TIME;
RUN;

**Problem7-9;

DATA DIR1.TREE;
	INPUT TYPE $ LOCATION $ HEIGHT;
DATALINES;
PINE NORTH 35
PINE NORTH 37
PINE NORTH 41
MAPLE NORTH 44
MAPLE NORTH 41
PINE SOUTH 53
PINE SOUTH 55
MAPLE SOUTH 28
MAPLE SOUTH 33
MAPLE SOUTH 32
MAPLE SOUTH 22
;
**PROC ANOVA DATA=DIR1.TREE SINCE IT IS AN UNBALANCED DATASET WHICH WE ARE WORKING WITH, USE GLM INSTEAD OF ANOVA;
PROC GLM DATA=DIR1.TREE;
TITLE "DIFFERENCE IN HEIGHTS BASED ON LOCATION AND TYPE";
CLASS TYPE LOCATION;
MODEL HEIGHT=TYPE | LOCATION;
MEANS TYPE LOCATION TYPE*LOCATION;
RUN;


ODS PDF CLOSE;
